import { Shipment } from './types';

export const TRACKING_STEPS = [
  { status: 'Order Placed', date: 'May 01, 2024, 10:00 AM', location: 'London, UK' },
  { status: 'Processed', date: 'May 01, 2024, 02:30 PM', location: 'London Hub' },
  { status: 'In Transit', date: 'May 02, 2024, 09:00 AM', location: 'English Channel' },
  { status: 'Arrived at Destination Country', date: 'May 03, 2024, 05:00 PM', location: 'Paris, France' },
  { status: 'Out for Delivery', date: 'May 04, 2024, 08:30 AM', location: 'Paris, France' },
];

export const DUMMY_SHIPMENTS: Shipment[] = [
  {
    id: '1',
    trackingNumber: 'SP-100234',
    sender: 'Global Tech Inc.',
    recipient: 'John Doe',
    origin: 'London, UK',
    destination: 'Paris, France',
    status: 'In Transit',
    orderDate: '2024-05-01',
    estimatedDelivery: '2024-05-05',
    carrier: 'DHL Express',
    weight: '2.5 kg',
    value: '$1,200',
  },
  {
    id: '2',
    trackingNumber: 'SP-100235',
    sender: 'Zara Fashion',
    recipient: 'Sarah Smith',
    origin: 'Madrid, Spain',
    destination: 'Berlin, Germany',
    status: 'Delivered',
    orderDate: '2024-04-28',
    estimatedDelivery: '2024-05-02',
    carrier: 'FedEx',
    weight: '1.2 kg',
    value: '$450',
  },
  {
    id: '3',
    trackingNumber: 'SP-100236',
    sender: 'Apple Store',
    recipient: 'Michael Brown',
    origin: 'San Francisco, USA',
    destination: 'New York, USA',
    status: 'Pending',
    orderDate: '2024-05-04',
    estimatedDelivery: '2024-05-08',
    carrier: 'UPS',
    weight: '0.8 kg',
    value: '$2,500',
  },
  {
    id: '4',
    trackingNumber: 'SP-100237',
    sender: 'Auto Parts Co.',
    recipient: 'Robert Wilson',
    origin: 'Detroit, USA',
    destination: 'Chicago, USA',
    status: 'Delayed',
    orderDate: '2024-04-30',
    estimatedDelivery: '2024-05-03',
    carrier: 'DHL Express',
    weight: '15 kg',
    value: '$800',
  },
];
